import argparse
import sys

from util import mask_to_json


def main():
    """
    main function to generate json file from masks files generated by Tiramisu
    """
    parser = argparse.ArgumentParser(
        description='convert masks generated by Tirmasu to json files.',
        prog='json_gen.py <args>')

    # Required arguments
    parser.add_argument("-i", "--input", required=True,
                        help="Path to masks generated by Tiramisu.")
    parser.add_argument("-o", "--output", required=True,
                        help="Path to save json file.")

    args = vars(parser.parse_args())
    mask_to_json(args['input'], args['output'])


if __name__ == "__main__":
    sys.exit(main())
